-- =====================================
-- V1__init_schema.sql
-- Initial schema for finance app
-- =====================================

-- === Table: users ===
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255),
    username VARCHAR(255),
    UNIQUE (email)
);

-- === Table: categories ===
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    is_income BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL
);

-- === Table: accounts ===
CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255),
    institution VARCHAR(255),
    balance NUMERIC(38,2) DEFAULT 0,
    created_at DATE DEFAULT CURRENT_DATE,
    user_id BIGINT NOT NULL
);

-- === Table: budgets ===
CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(38,2) NOT NULL,
    month DATE NOT NULL,
    category_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

-- === Table: goals ===
CREATE TABLE goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    target_amount NUMERIC(38,2) NOT NULL,
    current_amount NUMERIC(38,2) DEFAULT 0,
    due_date DATE,
    user_id BIGINT NOT NULL
);

-- === Table: transactions ===
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(38,2) NOT NULL,
    date DATE NOT NULL,
    is_recurring BOOLEAN DEFAULT FALSE,
    description VARCHAR(255),
    account_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL
);

-- === Foreign Key Constraints ===
ALTER TABLE accounts
    ADD CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE budgets
    ADD CONSTRAINT fk_budgets_category FOREIGN KEY (category_id) REFERENCES categories,
    ADD CONSTRAINT fk_budgets_user FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE categories
    ADD CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE goals
    ADD CONSTRAINT fk_goals_user FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE transactions
    ADD CONSTRAINT fk_transactions_account FOREIGN KEY (account_id) REFERENCES accounts,
    ADD CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES categories;

-- === Indexes (optional for performance) ===
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_categories_user_id ON categories(user_id);
CREATE INDEX idx_accounts_user_id ON accounts(user_id);
CREATE INDEX idx_budgets_user_id ON budgets(user_id);
CREATE INDEX idx_transactions_account_id ON transactions(account_id);
